YebinYun/seb45_pre_025

- clientes/src/App.js
- clientes/src/components/Cartegory.js
- clientes/src/pages/Main.js
- Link 연결완료
- 불가한 페이지 접근불가 커서 on
> [Feat] 메인화면(로그인 전) 구현완료

- clientes/src/App.js
- clientes/src/components/Footer.js
- clientes/src/components/Header.js
- clientes/src/pages/Main.js
- 레이아웃 완성
- Link 이동 none 처리 완료
<br>
---
<br>
> **'useLocation'** 사용으로 **'App.js'** 에 경로 지정 완료.
>> ✨이후 푸터를 사용할 페이지가 있을 경우,
**'App.js'** 파일에 **'showFooterPaths'** 에 원하는 페이지 Link 넣기
> [Feat] 푸터 구현

- clientes/src/App.js
- clientes/src/components/Header.js
- clientes/src/pages/Tags.js
- clientes/src/pages/Users.js
> [Feat] 카테고리 기능구현 추가

- clientes/src/pages/Questions.js
> [Refactor] 병합

- clientes/src/App.js
- clientes/src/components/Cartegory.js
- clientes/src/components/SideCartegory.js
- clientes/src/pages/Home.js
- clientes/src/pages/QuestionsAsk.js
<br>
<br>
- ### 좌측 사이드 바 구현
<br>
> [Feat] 메인창, 질문창 구현

- clientes/package-lock.json
- clientes/package.json
- clientes/src/pages/QuestionsAsk.js
- 데이터 받아오는 로직 구현
- 제출버튼 새로 만듦
- 뷰 라이브러리 설치 예정
-  버튼에 호버 효과
> feat: 웹에디터 뷰 기능 구현중

- clientes/src/App.js
- clientes/src/components/Category.js
- clientes/src/components/HeaderOn.js
- clientes/src/components/SideCartegory.js
- clientes/src/pages/Main.js
- clientes/src/pages/Users.js
<br>
---
<br>
- 회원에 대한 정보를 받을 페이지가 필요할 것 같아 긴급으로 우선 구현
- 유저 이름까진 보여줄 수 있을 듯..
> [Feat] 푸터 이슈 수정, 유저정보 페이지 구현

- clientes/src/pages/QuestionsAsk.js
- clientes/src/pages/QuestionsId.js
-질문상세창 질문, 답변 뷰어 기능 구현 완료
-질문작성창 버튼 호버, 상태관리 보완
기능구현 추가로 할 예정임
질문상세창 댓글기능 구현 필요
> feat: QuestionsAsk, QuestionsId 상태관리 업데이트

- clientes/package-lock.json
- clientes/package.json
- clientes/src/App.js
- clientes/src/pages/Home.js
- clientes/src/pages/QuestionsAsk.js
- clientes/src/pages/QuestionsId.js
- 경로이름 변경 questions/id ----> quetions/veiw
- 질문상세 쿼리 questions/vew?id={id}
- 질문작성 questios/ask
- 질문수정 questions/ask?id={id}
<br>
- 질문작성 페이지에 질문 수정 로직도 같이 구현(질문수정 유저아이디 접근법 논의필요)
- 질문상세 페이지 로직구현중(유저아이디 접근법 논의필요)
> feat: questionsId, questionsAsk 기능 업데이트

- clientes/src/pages/Signup.js
> [Feat] 회원가입 유효성검사

- clientes/src/pages/Login.js
> [Feat] 로그인 유효성검사

- clientes/src/App.js
- clientes/src/components/HeaderOn.js
- clientes/src/pages/Login.js
- clientes/src/pages/Signup.js
`localStorage`에 `token` 확인 후 헤더 변경 기능 구현 완료
> [Feat] 로그인, 로그아웃 헤더 변경 기능

- clientes/src/index.css
- clientes/src/pages/Main.js
- tailwind.config.js
> [DESIGN] 메인창 에니메이션 효과 추가

- clientes/src/pages/QuestionsAsk.js
- clientes/src/pages/QuestionsId.js
> feat: 질문답변 기능 구현중

- README.md
- clientes/src/pages/Login.js
- clientes/src/pages/Signup.js
- clientes/src/pages/Users.js
- 리드미 토글 효과 추가
- 유저 페이지 회원 탈퇴 버튼 구현
- 로그인, 회원가입 구글 OAuth 연결 중
> [DESIGN] 리드미 수정, 유저페이지 회원탈퇴 버튼 구현

- clientes/src/pages/Signup.js
> [Feat] 구글 로그인 테스트

- clientes/src/App.js
- clientes/src/Auth.js
- clientes/src/pages/Login.js
- clientes/src/pages/Signup.js
> [Feat] 서버 연결

- clientes/src/components/Pagination.js
- clientes/src/pages/Questions.js
> [Feat] api 경로 수정

- clientes/src/pages/Login.js
> [Test] 서버 테스트

- clientes/src/pages/Questions.js
> [Test] Link 쿼리 수정
